service: engine-slack-bot-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
  pick-begginer-leader:
    handler: src/pick-begginer-leader.handler
    events:
      - schedule: cron(0 22 ? * SAT *)
custom:
  webpackIncludeModules: true
plugins:
  - serverless-webpack
  - serverless-offline
